hosts:
  # hosts is a map from local-names to host specifications
  google:
    user_name: root
    host: google.com
    port: 22
  # You also have the option to leave the port field off for a
  # default value of 22
  facebook:
    user_name: root
    host: 192.168.1.1
